# Generated by Django 4.2.5 on 2023-09-26 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('id_account', models.IntegerField(primary_key=True, serialize=False, verbose_name='Account ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('api_id', models.IntegerField(blank=True, null=True, verbose_name='API ID')),
                ('api_hash', models.CharField(blank=True, max_length=100, null=True, verbose_name='API HASH')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Телефон')),
                ('status', models.BooleanField(default=True, verbose_name='Состояние')),
                ('report', models.TextField(blank=True, max_length=1000000, null=True, verbose_name='Отчёт о состоянии')),
                ('session', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сессия')),
                ('common_text', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Текст Рассылки')),
                ('auto_answering_text', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Текст автоответчика')),
                ('is_auto_answering_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Автоответчик вкл/выкл')),
                ('is_spam_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Спам вкл/выкл')),
                ('delay', models.IntegerField(blank=True, default=0, null=True, verbose_name='Задержка отправки сообщения (в минутах)')),
                ('master_to_forward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кому пересылать сообщения')),
            ],
            options={
                'verbose_name': 'Спам Аккаунт',
                'verbose_name_plural': 'Спам Аккаунты',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('title', models.CharField(blank=True, max_length=1000, verbose_name='Название чата')),
                ('username', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка или Юзернейм')),
                ('text', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Текст для чата')),
                ('last_message_id', models.IntegerField(blank=True, null=True, verbose_name='ID послежднего сообщения')),
                ('last_message_time', models.DateTimeField(blank=True, null=True, verbose_name='Последний раз отправлено')),
                ('delay', models.IntegerField(blank=True, default=0, null=True, verbose_name='Задержка отправки сообщения (в минутах)')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spambotapp.account', verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Группа для Спама',
                'verbose_name_plural': 'Группы для Спама',
                'db_table': 'chat',
                'unique_together': {('account', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Телефон')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('next_time_contact', models.DateTimeField(blank=True, null=True, verbose_name='Время следующего контакта')),
                ('exchange_time', models.DateTimeField(blank=True, null=True, verbose_name='Когда поменял')),
                ('exchange_value', models.TextField(blank=True, max_length=100, null=True, verbose_name='Сколько поменял')),
                ('is_spam_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Включён в рассылку')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='MasterAccount',
            fields=[
                ('id_account', models.IntegerField(primary_key=True, serialize=False, verbose_name='Account ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('api_id', models.IntegerField(blank=True, null=True, verbose_name='API ID')),
                ('api_hash', models.CharField(blank=True, max_length=100, null=True, verbose_name='API HASH')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone')),
                ('status', models.BooleanField(default=True, verbose_name='Состояние')),
                ('report', models.TextField(blank=True, max_length=1000000, null=True, verbose_name='Отчёт о состоянии')),
                ('session', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сессия')),
                ('is_master', models.BooleanField(blank=True, default=False, null=True, verbose_name='Мастер')),
                ('is_duplicate', models.BooleanField(blank=True, default=False, null=True, verbose_name='Дубликат')),
            ],
            options={
                'verbose_name': 'Мастер аккаунт',
                'verbose_name_plural': 'Мастер Аккаунты',
                'db_table': 'masteraccount',
            },
        ),
        migrations.CreateModel(
            name='GeneralLogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(blank=True, choices=[('Trace', 'Trace'), ('Debug', 'Debug'), ('Info', 'Info'), ('Warning', 'Warning'), ('Fatal', 'Fatal')], max_length=50, null=True, verbose_name='Уровень логгирования')),
                ('message', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Сообщение')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spambotapp.account', verbose_name='Аккаунт')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spambotapp.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Лог общий',
                'verbose_name_plural': 'Логи общие',
                'db_table': 'commonlogging',
            },
        ),
        migrations.CreateModel(
            name='AccountLogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(blank=True, choices=[('Trace', 'Trace'), ('Debug', 'Debug'), ('Info', 'Info'), ('Warning', 'Warning'), ('Fatal', 'Fatal')], max_length=50, null=True, verbose_name='Уровень логгирования')),
                ('message', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Сообщение')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spambotapp.account', verbose_name='Аккаунт')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spambotapp.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Лог аккаунта',
                'verbose_name_plural': 'Логи аккаунтов',
                'db_table': 'accountlogging',
            },
        ),
    ]
