# Generated by Django 4.2.5 on 2023-09-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spambotapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1000, verbose_name='Bot Token (‼️ не трогать ‼️)')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Бот',
            },
        ),
    ]
