# Generated by Django 4.2.5 on 2023-09-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spambotapp', '0002_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='link',
            field=models.CharField(default='', max_length=1000, verbose_name='Ссылка на бота (‼️ не трогать ‼️)'),
            preserve_default=False,
        ),
    ]
