# Generated by Django 4.2.5 on 2023-09-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spambotapp', '0003_bot_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='User ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='User Name')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Админ',
                'verbose_name_plural': 'Админы',
            },
        ),
    ]
