# Generated by Django 4.2.5 on 2023-09-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spambotapp', '0005_alter_chat_title_alter_chat_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='User ID')),
                ('add_chat', models.BooleanField(default=True, verbose_name='чат')),
                ('add_chat_text', models.BooleanField(default=True, verbose_name='чат')),
                ('add_chat_timeout', models.BooleanField(default=True, verbose_name='чат')),
                ('add_account', models.BooleanField(default=True, verbose_name='чат')),
                ('add_admin', models.BooleanField(default=True, verbose_name='чат')),
                ('add_auto_answering', models.BooleanField(default=True, verbose_name='чат')),
                ('set_timeout', models.BooleanField(default=True, verbose_name='чат')),
                ('set_price', models.BooleanField(default=True, verbose_name='чат')),
                ('set_general_text', models.BooleanField(default=True, verbose_name='чат')),
            ],
        ),
    ]
