# Generated by Django 4.2.5 on 2023-09-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spambotapp', '0006_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='id',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='add_account',
            field=models.BooleanField(blank=True, default=False, verbose_name='добавить аккаунт'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='add_admin',
            field=models.BooleanField(blank=True, default=False, verbose_name='добавить админа'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='add_auto_answering',
            field=models.BooleanField(blank=True, default=False, verbose_name='добавить автоответчик'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='add_chat',
            field=models.BooleanField(blank=True, default=False, verbose_name='добавить чат'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='add_chat_text',
            field=models.BooleanField(blank=True, default=False, verbose_name='добавить текст для чата'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='add_chat_timeout',
            field=models.BooleanField(blank=True, default=False, verbose_name='добавить задержку чату'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='set_general_text',
            field=models.BooleanField(blank=True, default=False, verbose_name='изменить общий текст'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='set_price',
            field=models.BooleanField(blank=True, default=False, verbose_name='изменить цену'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='set_timeout',
            field=models.BooleanField(blank=True, default=False, verbose_name='изменить общую задержку'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='User ID'),
        ),
    ]
