# Generated by Django 4.2.5 on 2023-09-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spambotapp', '0007_remove_usersettings_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_spam_lk_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Спам по ЛС вкл/выкл'),
        ),
    ]
