# Generated by Django 4.2.5 on 2023-09-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spambotapp', '0008_account_is_spam_lk_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена 1')),
                ('price_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена 2')),
                ('price_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена 3')),
                ('price_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена 4')),
            ],
            options={
                'verbose_name': 'Общие настройки',
                'verbose_name_plural': 'Общие настройки',
            },
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
