# Generated by Django 4.2.5 on 2023-09-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spambotapp', '0009_generalsettings_delete_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='forward_lk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пересыл в ЛС'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='general_auto_answering',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Общий автоответчик'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='general_delay',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общая задержка отправки сообщения (в минутах)'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='general_text',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Общий Текст'),
        ),
    ]
