# Generated by Django 4.2.5 on 2023-09-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spambotapp', '0010_generalsettings_forward_lk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgadmin',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tgadmin',
            name='last_name',
        ),
    ]
