# Generated by Django 4.2.5 on 2023-09-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spambotapp', '0011_remove_tgadmin_first_name_remove_tgadmin_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgadmin',
            name='id',
        ),
        migrations.AlterField(
            model_name='tgadmin',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='User ID'),
        ),
    ]
