# Generated by Django 4.2.5 on 2023-09-29 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spambotapp', '0012_remove_tgadmin_id_alter_tgadmin_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='account',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='last_message_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='last_message_time',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID сообщения')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('last_message_id', models.IntegerField(blank=True, null=True, verbose_name='ID последнего сообщения')),
                ('last_message_time', models.DateTimeField(blank=True, null=True, verbose_name='Последний раз отправлено')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spambotapp.account', verbose_name='Аккаунт')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spambotapp.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'message',
                'unique_together': {('account', 'chat')},
            },
        ),
    ]
