# Generated by Django 4.2.5 on 2023-09-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spambotapp', '0013_alter_chat_unique_together_remove_chat_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='last_message_id',
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Удалено из группы'),
        ),
    ]
