# Generated by Django 4.2.5 on 2023-10-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spambotapp', '0015_remove_message_last_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sms_code',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='SMS код'),
        ),
    ]
