# Generated by Django 4.2.5 on 2023-10-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spambotapp', '0016_account_sms_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='signed_in',
            field=models.BooleanField(blank=True, default=False, verbose_name='Активирован'),
        ),
    ]
